reportportal.baseUrl=http://localhost:8080/api/v1
reportportal.project=test_infra
reportportal.authToken=test-infra_iKPprGYfS96dyOQDD1tJfi7cRGhSu6zMrUolU9olbfnOdCrb8qWDE4O8CvxloIPc

# Analysis settings
analysis.scheduler.enabled=true
analysis.scheduler.interval=3600000  # 1 hour in milliseconds